service: sns-fastapi-service

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:CreateTopic"
        - "sns:Subscribe"
        - "sns:Unsubscribe"
      Resource: "*"

functions:
  api:
    handler: app.handler
    events:
      - http:
          path: /create-sns-topic
          method: post
      - http:
          path: /unsubscribe
          method: delete

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
